/**
 * DOCUMENT LAYOUT SYSTEM (v1)
 * 
 * Universal layout specification for all export/import documents.
 * Every document must follow this structure in this order.
 * This is the permanent system for the application.
 */

export const DOCUMENT_LAYOUT_SYSTEM = {
  version: "1.0",
  timestamp: "2026-02-16",
  applicableDocuments: [
    "Commercial Invoice",
    "Packing List",
    "Shipping Bill (Draft)",
    "Declaration / Undertaking",
    "Certificate of Origin (Draft)",
    "Insurance Declaration",
    "LC Supporting Documents",
  ],

  visualPhilosophy: {
    title: "Invoice v1.1 Design Direction - Visual Philosophy",
    purpose: "Guiding principles for all document design and implementation",
    
    lockedVisualDirection: {
      status: "LOCKED DECISION - PURE BLACK & WHITE",
      timestamp: "2026-02-16",
      authority: "Institutional Compliance Architecture",
      decision: "Pure Black & White - No Greys. No Light Fills. No Soft Borders. No SaaS UI Styling.",
      rationale: {
        reason1: "Banks print documents in grayscale - color information is lost",
        reason2: "Customs authorities photocopies documents for filing - subtle colors disappear",
        reason3: "Embassies scan documents to microfilm - grey tones become illegible",
        reason4: "Legal systems distrust decorative design - institutional documents must look plain, official",
        reason5: "Export houses use plain black & white documents - must match seasoned institutional aesthetic (not startup UI)",
      },
      implementation: {
        textColor: "#000000 (pure black, no dark grey alternatives)",
        backgroundColor: "#ffffff (pure white, no off-white alternatives)",
        borders: "1px solid #000000 (black only - no soft grey borders)",
        roundedCorners: "FORBIDDEN - All corners are sharp/right-angles",
        decorativeElements: "FORBIDDEN - No shadows, no fills, no gradients, no effects",
        lineWeights: "1px black lines only for structure (no varying weights, no soft edges)",
      },
      violationConsequences: {
        usingGrey: "CRITICAL - Violates grayscale print compliance. Will fail customs clearance.",
        usingSoftBorders: "CRITICAL - Fails bureaucratic document test. Will be rejected by banks.",
        roundedCorners: "CRITICAL - Looks like SaaS, not export house. Violates institutional authenticity.",
        colorFills: "CRITICAL - Disappears in photocopies/scans. Breaks document integrity.",
      },
      approved: true,
      applicableToAllDocuments: true,
    },

    lockedInstitutionalTone: {
      status: "LOCKED DECISION - REGULATORY SUBTITLE",
      timestamp: "2026-02-16",
      authority: "Institutional Trust Architecture",
      decision: "All documents include: (Issued under FEMA & RBI Guidelines)",
      subtitle: "(Issued under FEMA & RBI Guidelines)",
      styling: {
        fontSize: "10px",
        fontWeight: "400",
        color: "#000000",
        textAlign: "center",
        position: "Directly below document title",
        spacing: "8px above, 16px below title divider",
      },
      rationale: {
        reason1: "Signals regulatory compliance awareness to banks and customs",
        reason2: "Builds trust instantly with export community (shows regulatory knowledge)",
        reason3: "Conveys traditional exporter aesthetic (not startup style)",
        reason4: "Institutional tone - subtle, not flashy",
      },
      purpose: "Three functions: [1] Regulatory signal, [2] Trust builder, [3] Traditional style indicator",
      designPrinciple: "Subtle institutional marker. Affects credibility and regulatory perception.",
      approved: true,
      applicableToAllDocuments: true,
    },

    lockedWatermarkPolicy: {
      status: "LOCKED DECISION - SUBTLE FREE-PLAN WATERMARK",
      timestamp: "2026-02-16",
      authority: "Plan Enforcement + Institutional Brand Confidence",
      decision: "Add watermark only on Free plan documents.",
      appliesTo: {
        freePlan: true,
        proPlan: false,
      },
      content: {
        text: "GENERATED VIA PLATFORM",
        textTransform: "uppercase",
        fontFamily: "sans-serif",
      },
      styling: {
        opacity: "5.5% (range 5% to 6%)",
        position: "Centered diagonal",
        rotation: "-32° to -35°",
        color: "#000000",
        visualWeight: "Very light, subtle",
      },
      rationale: {
        reason1: "Loud watermark signals insecurity and startup immaturity",
        reason2: "Subtle watermark communicates confidence and professional control",
        reason3: "Free-plan differentiation remains visible without degrading document trust",
      },
      designPrinciple: "Subtle watermark = confident product. Never loud.",
      approved: true,
      applicableToAllDocuments: true,
      immutabilityViolations: [
        "Cannot show watermark on Pro plan (violation severity: CRITICAL)",
        "Cannot exceed 6% opacity (violation severity: HIGH)",
        "Cannot use non-diagonal placement (violation severity: HIGH)",
        "Cannot change text from 'GENERATED VIA PLATFORM' (violation severity: HIGH)",
      ],
    },
    
    principles: {
      minimalism: {
        title: "White Space Does The Work",
        description: "Rely on spacing, alignment, and typography to create hierarchy and guide the eye",
        implementation: [
          "Generous margins (20mm top/bottom, 18mm sides)",
          "32px section spacing for visual separation",
          "8px row spacing for breathing room within sections",
          "Never use background colors or shading to create structure",
          "Let content density and whitespace define sections",
        ],
        examples: [
          "Party information uses 32px column gap, not boxes",
          "Line items separated by light borders, not alternating backgrounds",
          "Summary uses spacing, not shaded container",
        ],
      },
      
      noBorders: {
        title: "Only Black Lines - No Grey, No Soft Edges",
        description: "Remove all visual clutter except essential thin black lines for structure",
        implementation: [
          "Only 1px solid black (#000000) for borders",
          "Section headers have 1px solid black bottom border only",
          "Table structure via 1px solid black horizontal lines exclusively",
          "No vertical borders, no grids, no outside frames",
          "No grey borders, no soft borders, no feathered edges",
          "No decorative elements of any kind",
        ],
        exceptions: [],
        designPrinciple: "Clean, harsh institutional aesthetic - no compromises for visual softness",
      },
      
      typography: {
        title: "Strong Typography Hierarchy - Only Black Text",
        description: "Typography carries all visual weight since borders and colors are minimal",
        implementation: [
          "Document title: 26px, 700 weight, #000000 (commands attention)",
          "Section headers: 11px, 600 weight, uppercase, #000000 (clear segmentation)",
          "Labels: 12px, 500 weight, #000000 (guides reading order)",
          "Body text: 13px, 400 weight, #000000 (comfortable reading)",
          "Footer: 10px, 400 weight, #000000 (subordinate but still readable)",
          "Tables: header 12px 600, body 13px 400, #000000 (mathematical precision)",
        ],
        colorPalette: [
          "PRIMARY: #000000 (black text for all content)",
          "BACKGROUND: #ffffff (white only)",
          "NO GREYS ALLOWED - No #111827, #374151, #6b7280, #9ca3af, #d1d5db, #e5e7eb, #f3f4f6",
        ],
      },
      
      tables: {
        title: "Clean Black Table Lines - Mathematically Rigid",
        description: "Tables must feel precise, professional, and trustworthy for financial data",
        implementation: [
          "Header row: 1px solid black (#000000) bottom border, uppercase labels, 12px 600 weight, black text",
          "Data rows: 1px solid black (#000000) bottom border, 13px 400 weight, black text",
          "Last row: 1px solid black (#000000) bottom border - same weight to close table",
          "Column alignment: text left, numbers right, codes monospaced",
          "No alternating row backgrounds, no vertical lines, no shading, NO GREY BORDERS",
          "Tab-numeric font variant for proper number alignment (fixed spacing)",
        ],
        purpose: "Rigorous tabular structure conveys mathematical accuracy and trustworthiness",
      },
      
      totals: {
        title: "Totals Section Must Feel Authoritative - Black Text Only",
        description: "Financial totals are critical and must command attention and authority",
        implementation: [
          "Right-aligned column (300px width)",
          "Subtotal: 13px 500 weight, #000000 (visible but not primary)",
          "Dividing line: 1px solid black (#000000) (clear separation)",
          "Total: 16px 700 weight, #000000 (commanding presence)",
          "Spacing: 8px row height emphasizes individual line items, then 12px padding around divider",
          "No shading or outer frame - authority comes from typography and spacing, not decoration",
        ],
        psychology: "Bold typography + careful spacing = financial trustworthiness without ornament",
      },
      
      footer: {
        title: "Regulatory Footer Must Feel Official - Pure Black & White",
        description: "Footer is legal/audit document - must convey authority and seriousness",
        implementation: [
          "10px black text (#000000) - small but not invisible",
          "Top border 1px solid black (#000000) - clear frame separator",
          "Single-line layout with black bullet separators (•)",
          "Multiple metadata fields: brand • timestamp • hash • audit ID",
          "Monospace font for hash values (conveys technical precision)",
          "Center-aligned - focused, official tone",
        ],
        fields: [
          "Generated by [Brand] - establishes source",
          "Timestamp - audit trail",
          "Document Hash - digital verification capability",
          "Audit ID - regulatory reference",
        ],
        psychology: "Small, precise, auditable data = official compliance document",
      },
    },
    
    designChecklist: {
      description: "Quick validation that a new document follows Invoice v1.1 design (Pure Black & White)",
      mustHave: [
        "☑ Document header with exporter info (left) and title/dates (right)",
        "☑ ONLY black (#000000) text, white (#ffffff) background",
        "☑ ONLY 1px solid black borders - no grey, no soft edges",
        "☑ No rounded corners anywhere - all right angles",
        "☑ Section headers: 11px 600 uppercase with 1px solid black bottom border only",
        "☑ Tables: 1px solid black borders (top header, between rows, bottom closure)",
        "☑ Section spacing: 32px gap between major blocks",
        "☑ Row spacing: 8px gap within blocks",
        "☑ Totals using spacing + 16px bold typography (not shading)",
        "☑ Footer: 10px black center-aligned with metadata and audit trail",
        "☑ Typography hierarchy: 26px title → 13px body → 10px footer (all black)",
      ],
      mustNotHave: [
        "✗ ANY grey colors (#111827, #374151, #6b7280, #9ca3af, #d1d5db, #e5e7eb, #f3f4f6)",
        "✗ Background colors except white (#ffffff)",
        "✗ Grey borders or soft edges",
        "✗ Heavy borders or grid lines (only 1px black)",
        "✗ Alternating row colors (white and white only)",
        "✗ Rounded corners on ANY element",
        "✗ Shadows, fills, gradients, or decorative effects",
        "✗ Centered body text (except footer)",
        "✗ Multiple font families (Inter + system fallbacks only)",
      ],
    },
    
    philosophy: {
      coreIdea: "Institutional Black & White. Pure. Official. Trustworthy. No design flourishes.",
      
      whyThisMatters: [
        "Banks print documents in grayscale - colour information is lost in printing",
        "Customs photocopies documents for archives - grey tones become illegible",
        "Embassies scan to microfilm - soft borders disappear in scanning",
        "Legal systems distrust decorative design - plain documents convey official authority",
        "Export houses use black & white documents - must match institutional aesthetic, not startup UI",
      ],
      
      forbidden: [
        "CRITICAL: Any grey color (#111827, #374151, #6b7280, #9ca3af, #d1d5db, #e5e7eb, #f3f4f6)",
        "CRITICAL: Any background color except white (#ffffff)",
        "CRITICAL: Rounded corners on any element",
        "CRITICAL: Soft/feathered borders (use 1px solid black only)",
        "Gradients, shadows, boxed containers, color fills, heavy fonts, centered body text, script fonts, italics for emphasis",
      ],
      
      allowed: [
        "Black text (#000000)",
        "White background (#ffffff)",
        "1px solid black borders (#000000)",
        "Right-angle corners only",
        "White space and spacing for hierarchy",
        "Bold typography for emphasis",
        "Monospace fonts for code/hash values",
        "Uppercase labels for guidance",
        "Numeric right-alignment for financial data",
      ],
      
      colorPaletteApproved: {
        status: "LOCKED - PURE BLACK & WHITE ONLY",
        primaryText: {
          color: "#000000",
          usage: "All text content - headers, body, labels, values",
          hexCode: "000000",
          rgbCode: "rgb(0, 0, 0)",
        },
        background: {
          color: "#ffffff",
          usage: "Page background and all cell backgrounds",
          hexCode: "ffffff",
          rgbCode: "rgb(255, 255, 255)",
        },
        borders: {
          color: "#000000",
          usage: "All lines, borders, dividers (1px solid only)",
          weight: "1px",
          style: "solid",
          hexCode: "000000",
          rgbCode: "rgb(0, 0, 0)",
        },
        forbiddenColors: {
          deprecated: "#111827, #374151, #6b7280, #9ca3af, #d1d5db, #e5e7eb, #f3f4f6",
          reason: "These greys are used in current implementation but MUST be replaced with either #000000 or #ffffff",
          action: "Code review must identify and replace all grey color references",
        },
      },
    },
  },

  colorMigrationGuide: {
    status: "IMMEDIATE ACTION REQUIRED",
    purpose: "Map deprecated grey colors to approved black/white palette",
    timestamp: "2026-02-16",
    
    colorReplacements: {
      old_111827_darkGrey: {
        deprecated: "#111827 (very dark grey - currently used for primary text)",
        replacement: "#000000 (pure black)",
        reasoning: "Primary text must be pure black for print clarity",
        affectedAreas: [
          "Document titles (26px 700)",
          "Primary labels (12px 500-600)",
          "Body text (13px 400)",
          "Total amounts (16px 700)",
        ],
      },
      old_374151_mediumGrey: {
        deprecated: "#374151 (medium grey - currently used for secondary text)",
        replacement: "#000000 (pure black)",
        reasoning: "Secondary text must still be black for readability in grayscale printing",
        affectedAreas: [
          "Section labels",
          "Item descriptions",
          "Address information",
          "Secondary metadata",
        ],
      },
      old_6b7280_lightGrey: {
        deprecated: "#6b7280 (light grey - currently used for tertiary text/guidance)",
        replacement: "#000000 (pure black)",
        reasoning: "Light greys disappear in photocopies and scans - use black with weight/size variation instead",
        alternative: "Use lighter font-weight (400) or smaller font-size (10px) instead of grey color",
        affectedAreas: [
          "Section headers uppercase labels",
          "Form labels",
          "Tertiary information",
        ],
      },
      old_9ca3af_veryLightGrey: {
        deprecated: "#9ca3af (very light grey - currently used for footer/subtle text)",
        replacement: "#000000 (pure black) with font-size 10px",
        reasoning: "Footer text must be readable and official even if small",
        affectedAreas: [
          "Page numbers",
          "Footer metadata",
          "Audit trail information",
          "Generation timestamp",
        ],
      },
      old_d1d5db_softBorderGrey: {
        deprecated: "#d1d5db (soft grey border - currently used for table/section borders)",
        replacement: "#000000 (pure black, 1px solid)",
        reasoning: "Soft grey borders disappear in grayscale printing - use hard black lines only",
        affectedAreas: [
          "Table header bottom borders",
          "Section dividers",
          "Financial summary divider",
        ],
      },
      old_e5e7eb_veryLightBorder: {
        deprecated: "#e5e7eb (very light grey border)",
        replacement: "#000000 (pure black, 1px solid) OR #ffffff (white, if needing visual separation within white)",
        reasoning: "Light borders are invisible in print",
        alternative: "Use white background above/below for spacing instead of soft grey line",
      },
      old_f3f4f6_almostWhiteGrey: {
        deprecated: "#f3f4f6 (almost-white grey - currently used as subtle dividers)",
        replacement: "#ffffff (pure white) for background OR #000000 for borders",
        reasoning: "This grey is essentially white but creates false visual hierarchy",
        alternative: "Use pure white background and black 1px lines for structure",
      },
    },
    
    implementationChecklist: {
      "Find-Replace Operations": [
        "⚠️ Replace all #111827 with #000000 (except verify context first)",
        "⚠️ Replace all #374151 with #000000 (except verify context first)",
        "⚠️ Replace all #6b7280 with #000000 or adjust font-weight/size (check context)",
        "⚠️ Replace all #9ca3af with #000000 at 10px font-size",
        "⚠️ Replace all #d1d5db borders with 1px solid #000000",
        "⚠️ Replace all #e5e7eb with #000000 or #ffffff (check context)",
        "⚠️ Replace all #f3f4f6 with #ffffff or spacing adjustments",
      ],
      
      filesMustBeAudited: [
        "lib/htmlInvoiceTemplate.ts - CSS color definitions",
        "lib/documentLayoutSystem.ts - Color references in specifications",
        "All generated documents must render in pure black & white",
      ],
      
      testingRequirements: [
        "Print test page in grayscale - no grey text should appear invisible",
        "Photocopy test page - all text must remain readable",
        "PDF export test - all borders must be visible at 1px",
        "Screen reader test - no color-dependent info should be lost",
      ],
    },
  },

  structure: [
    {
      order: 0,
      section: "FROZEN INVOICE STRUCTURE SPINE",
      purpose: "Permanent header layout for all 7 document types - IMMUTABLE authority block design",
      philosophy: "This is a document that goes to a bank.",
      applicableToAllDocuments: true,
      position: "Top of every page",
      layout: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: "40px",
        marginBottom: "40px",
        pageBreak: "page-break-inside: avoid",
      },
      columns: {
        left: {
          title: "Document Identity (Title + Invoice Metadata)",
          position: "Top-left corner (non-negotiable)",
          content: [
            "Document Title (COMMERCIAL INVOICE, PACKING LIST, etc.)",
            "Invoice No. (13px 500wt #000)",
            "Date (12px 400wt #000)",
          ],
          styling: {
            layout: "flex column with 12px gap",
            purpose: "Clear document identification + regulatory metadata",
          },
          components: {
            title: {
              element: "H1 - Document Title",
              fontSize: "26px",
              fontWeight: "700",
              letterSpacing: "0.5px",
              color: "#111827",
              lineHeight: "1.2",
              marginBottom: "12px",
              paddingBottom: "16px",
              borderBottom: "1px solid #111827",
              cssClass: ".document-title",
              designNote: "Thin divider (1px solid black) below title for visual finality and institutional weight",
            },
            invoiceNumber: {
              element: "Invoice No.",
              fontSize: "13px",
              fontWeight: "500",
              color: "#000",
              letterSpacing: "0.4px",
              philosophy: "Quiet, official, compliant. Not oversized. Not colored. Not badged.",
              tone: "Trade finance, not Dribbble",
              cssClass: ".invoice-number",
              immutable: "POSITION LOCKED - Will not change across all 7 document types",
            },
            date: {
              element: "Date",
              fontSize: "12px",
              fontWeight: "400",
              color: "#000",
              philosophy: "Subordinate but still visible.",
              cssClass: ".invoice-date",
            },
            pageNumber: {
              element: "Page Number",
              text: "Page 1 of 1",
              fontSize: "10px",
              fontWeight: "400",
              color: "#9ca3af",
              position: "Bottom right corner of page",
              cssClass: ".page-number",
              displayRule: "Always visible (absolute positioning)",
              immutable: true,
              designNote: "Small, neutral pagination indicator positioned absolutely in bottom-right",
            },
            regulatorySubtitle: {
              element: "Subtitle - Regulatory Authority Statement",
              text: "(Issued under FEMA & RBI Guidelines)",
              fontSize: "10px",
              fontWeight: "400",
              color: "#111827",
              textAlign: "center",
              position: "Directly below document title, before invoice metadata",
              cssClass: ".regulatory-subtitle",
              displayRule: "Always visible on all documents",
              immutable: true,
              purpose: "Signal regulatory compliance (FEMA & RBI) + build institutional trust + convey traditional exporter aesthetic",
              designNote: "Subtle, not flashy. Signals FEMA (Foreign Exchange Management Act) and RBI (Reserve Bank of India) compliance awareness. Signals regulatory awareness to banks and customs. Builds trust instantly with export community.",
            },
          },
        },
        right: {
          title: "Authority Block (Exporter + Compliance)",
          position: "Top-right corner (with visual separator)",
          design: "Projects regulatory authority - this is a bank document",
          visualFeature: "2px left border #e5e7eb + 24px padding creates separation hierarchy",
          content: [
            "Exporter Legal Name (13px 600 bold)",
            "IEC (12px 500 uppercase precision)",
            "GSTIN (12px 500 uppercase precision)",
            "AD Code (11px 500 uppercase for customs)",
            "Payment Terms (LC / DA / DP / Advance)",
          ],
          styling: {
            layout: "flex column with 8px gap",
            separator: "2px solid #e5e7eb left border + 24px padding",
            purpose: "Clear regulatory/compliance authority",
          },
          components: {
            exporterName: {
              element: "Exporter Name",
              fontSize: "13px",
              fontWeight: "600",
              color: "#111827",
              lineHeight: "1.4",
              cssClass: ".exporter-name",
            },
            iec: {
              element: "IEC",
              fontSize: "12px",
              fontWeight: "500",
              color: "#111827",
              letterSpacing: "0.3px",
              purpose: "Regulatory ID - precision matters",
              cssClass: ".exporter-iec",
              condition: "Only if exporter.iec populated",
            },
            gstin: {
              element: "GSTIN",
              fontSize: "12px",
              fontWeight: "500",
              color: "#111827",
              letterSpacing: "0.3px",
              purpose: "Tax ID - precise formatting",
              cssClass: ".exporter-gstin",
              condition: "Only if exporter.gstIN populated",
            },
            adCode: {
              element: "AD Code",
              fontSize: "11px",
              fontWeight: "500",
              color: "#6b7280",
              textTransform: "uppercase",
              letterSpacing: "0.5px",
              purpose: "Customs authority code (when applicable)",
              cssClass: ".exporter-ad-code",
              condition: "Only if exporter.adCode populated",
            },
            paymentTerms: {
              element: "Payment Terms",
              fontSize: "12px",
              fontWeight: "600",
              color: "#111827",
              borderTop: "1px solid #e5e7eb",
              marginTop: "4px",
              paddingTop: "8px",
              purpose: "Payment method visible at glance (LC/DA/DP/Advance)",
              cssClass: ".payment-terms",
              condition: "Only if invoice.paymentTerms populated",
              values: "LC (Letter of Credit) | DA (Documents Against Acceptance) | DP (Documents Against Payment) | Advance",
            },
          },
        },
      },
      spacing: {
        headerBlockBottomMargin: "40px",
        leftRightGap: "40px",
        metadataGap: "12px (left column between elements)",
        authorityBlockGap: "8px (right column between elements)",
        leftBorderSeparator: "2px solid #e5e7eb",
      },
      cssClasses: {
        container: ".document-header",
        left: ".header-left",
        right: ".header-right",
        title: ".document-title",
        invoiceNumber: ".invoice-number",
        invoiceDate: ".invoice-date",
        exporterName: ".exporter-name",
        iec: ".exporter-iec",
        gstin: ".exporter-gstin",
        adCode: ".exporter-ad-code",
        paymentTerms: ".payment-terms",
      },
      metadata: {
        designRationale: "Bank document structure lock - Trade finance scrutiny over Dribbble awards.",
      },
      immutability: {
        status: "FROZEN - No repositioning for any document type",
        rationale: "Bank scrutiny requires consistent document structure. Regulatory audit trail clarity.",
        applies: "Commercial Invoice, Packing List, Shipping Bill, Declaration, Certificate of Origin, Insurance Declaration, LC Supporting Docs",
        violationConsequence: "If structure is changed, compliance audit will fail",
      },
      bankDocumentPrinciples: {
        principle1: "Invoice # visible immediately top-left",
        principle2: "Date visible immediately top-left",
        principle3: "Exporter authority clearly identified in right authority block",
        principle4: "Regulatory codes (IEC/GSTIN) in authority block with precision formatting",
        principle5: "Payment terms visible at glance in authority block",
        principle6: "Left-right visual separation with 2px border creates hierarchy",
        principle7: "No decorative elements - only regulatory precision",
      },
      standardization: {
        applies: "All 7 document types",
        consistency: "FROZEN INVOICE STRUCTURE SPINE - Identical header structure across all documents",
        immutable: "No repositioning allowed for any document type",
        rationale: "Bank scrutiny, regulatory audit trails, scanning efficiency",
      },
    },

    {
      order: 1,
      section: "EXPORTER / BUYER BLOCK (Clean Two-Column Grid)",
      purpose: "Identify parties involved in transaction - standardized across all 7 documents",
      applicableToAllDocuments: true,
      position: "Immediately after document header (after 40px margin-bottom)",
      philosophy: "No fancy styling. Just alignment. Serious spacing.",
      layout: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: "32px",
        marginBottom: "32px",
        pageBreak: "page-break-inside: avoid",
      },
      columns: {
        left: {
          title: "Exporter / Shipper",
          content: [
            "Legal Name (bold, 13px 600)",
            "Full Address (12px 400)",
            "IEC (if applicable)",
            "GSTIN (if applicable)",
          ],
          styling: {
            layout: "flex column",
            alignment: "left-aligned",
            noBackground: true,
            noBorder: true,
          },
        },
        right: {
          title: "Buyer / Importer",
          content: [
            "Legal Name (bold, 13px 600)",
            "Full Address (12px 400)",
            "Country (if applicable)",
          ],
          styling: {
            layout: "flex column",
            alignment: "left-aligned",
            noBackground: true,
            noBorder: true,
          },
        },
      },
      sectionHeader: {
        element: "h3",
        fontSize: "12px",
        fontWeight: "600",
        color: "#6b7280",
        textTransform: "uppercase",
        letterSpacing: "0.6px",
        marginBottom: "12px",
        paddingBottom: "12px",
        borderBottom: "1px solid #e5e7eb",
        cssClass: ".section-title, h3",
      },
      content: {
        layout: "flex flex-col",
        gap: "8px",
        lineHeight: "1.6",
      },
      components: {
        name: {
          element: "p strong",
          fontSize: "13px",
          fontWeight: "600",
          color: "#111827",
          marginBottom: "0",
        },
        address: {
          element: "p",
          fontSize: "12px",
          fontWeight: "400",
          color: "#374151",
          marginBottom: "4px",
        },
        identifiers: {
          element: "p",
          fontSize: "12px",
          fontWeight: "400",
          color: "#374151",
          format: "Label: Value (e.g., IEC: ABC1234567)",
          marginBottom: "0",
        },
      },
      spacing: {
        columnGap: "32px (serious horizontal spacing)",
        contentGap: "8px (between rows)",
        bottomMargin: "32px (before next section)",
        noPadding: "true (clean alignment)",
      },
      cssClasses: {
        container: ".info-grid",
        left: ".info-section:first-child",
        right: ".info-section:last-child",
        header: "h3",
        content: ".info-content",
      },
      immutability: {
        status: "FROZEN - Two-column grid structure immutable",
        rationale: "Clean visual hierarchy, regulatory clarity, consistent party identification",
        applies: "All 7 document types",
      },
      designPrinciples: {
        principle1: "No background colors or shading",
        principle2: "No borders (except section title divider)",
        principle3: "Left-aligned content only",
        principle4: "32px gap creates visual separation without decoration",
        principle5: "Section headers follow universal 12px 600 uppercase pattern",
        principle6: "Content uses locked typography (13px names, 12px addresses)",
      },
    },

    {
      order: 2,
      section: "SHIPMENT & TRADE BLOCK (Minimal + Essential)",
      purpose: "Trade compliance and logistics details - standardized across all 7 documents",
      applicableToAllDocuments: true,
      position: "After Exporter/Buyer block (after 32px margin-bottom)",
      philosophy: "Minimal separators. No grey boxes.",
      components: [
        "Incoterm (FOB, CIF, CFR, CIP, DDP, etc.)",
        "Port of Loading (UN/LOCODE format)",
        "Port of Discharge (UN/LOCODE format)",
        "Country of Origin (ISO 3166 Code)",
        "Mode of Transport (Sea, Air, Road, Rail, Courier, Mixed)",
      ],
      layout: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr 1fr",
        gap: "40px",
        marginBottom: "32px",
        pageBreak: "page-break-inside: avoid",
      },
      items: {
        incoterm: {
          label: "Incoterm",
          fontSize: "12px",
          fontWeight: "600",
          color: "#6b7280",
          textTransform: "uppercase",
          letterSpacing: "0.6px",
          valueSize: "13px",
          valueWeight: "400",
          valueColor: "#374151",
          cssClass: ".shipment-item",
          immutable: true,
          condition: "Always present",
        },
        portOfLoading: {
          label: "Port of Loading",
          fontSize: "12px",
          fontWeight: "600",
          color: "#6b7280",
          textTransform: "uppercase",
          letterSpacing: "0.6px",
          valueSize: "13px",
          valueWeight: "400",
          valueColor: "#374151",
          cssClass: ".shipment-item",
          format: "UN/LOCODE (e.g., USNYC = New York, US)",
          immutable: true,
          condition: "Always present (non-negotiable structural rule)",
        },
        portOfDischarge: {
          label: "Port of Discharge",
          fontSize: "12px",
          fontWeight: "600",
          color: "#6b7280",
          textTransform: "uppercase",
          letterSpacing: "0.6px",
          valueSize: "13px",
          valueWeight: "400",
          valueColor: "#374151",
          cssClass: ".shipment-item",
          format: "UN/LOCODE (e.g., SGSIN = Singapore)",
          immutable: true,
          condition: "Always present (non-negotiable structural rule)",
        },
        countryOfOrigin: {
          label: "Country of Origin",
          fontSize: "12px",
          fontWeight: "600",
          color: "#6b7280",
          textTransform: "uppercase",
          letterSpacing: "0.6px",
          valueSize: "13px",
          valueWeight: "400",
          valueColor: "#374151",
          cssClass: ".shipment-item",
          format: "ISO 3166 Alpha-2 (e.g., IN = India, US = USA)",
          immutable: true,
          condition: "Always present (compliance audit requirement)",
        },
        modeOfTransport: {
          label: "Mode of Transport",
          fontSize: "12px",
          fontWeight: "600",
          color: "#6b7280",
          textTransform: "uppercase",
          letterSpacing: "0.6px",
          valueSize: "13px",
          valueWeight: "400",
          valueColor: "#374151",
          cssClass: ".shipment-item",
          values: "Sea | Air | Road | Rail | Courier | Mixed",
          immutable: true,
          condition: "Always present",
        },
      },
      styling: {
        container: ".shipment-details",
        labelClass: ".shipment-item-label",
        valueClass: ".shipment-item-value",
        noBackground: true,
        noBorder: true,
        minimalSeparators: "No dividers between items, no grey boxes, gap-only separation",
      },
      spacing: {
        columnGap: "40px (serious horizontal spacing)",
        bottomMargin: "32px (before next section)",
        labelMarginBottom: "6px (between label and value)",
      },
      immutability: {
        status: "FROZEN - Five-item trade block structure immutable",
        rationale: "Bank scrutiny requires consistent trade compliance data. Regulatory audit trail clarity.",
        applies: "All 7 document types",
        violationConsequence: "If items removed or reordered, customs audit trail breaks",
      },
      designPrinciples: {
        principle1: "Incoterm visible immediately (controls payment/risk allocation)",
        principle2: "Port of Loading visible immediately (customs tracking)",
        principle3: "Port of Discharge visible immediately (delivery authority)",
        principle4: "Country of Origin visible immediately (tariff classification)",
        principle5: "Mode of Transport visible immediately (logistics compliance)",
        principle6: "3-column grid layout for serious spacing (not cramped)",
        principle7: "No background colors or boxes - spacing carries hierarchy",
        principle8: "Labels uppercase 12px 600 with 0.6px letter-spacing (precision)",
        principle9: "Values 13px 400 #374151 (readable, not commanding attention)",
      },
    },

    {
      order: 3,
      section: "ITEMS TABLE (FROZEN INSTITUTIONAL)",
      immutability: {
        status: "FROZEN",
        reason: "Bank scrutiny requirement + HS Code tracking for customs + Inventory alignment",
        violationConsequence: "Will cause regulatory non-compliance and customs rejection",
        lastModified: "Current Session",
      },
      purpose: "Itemized breakdown with 7 institutional columns for customs and inventory tracking",
      applicableToAllDocuments: true,
      columnOrder: ["Sr", "Description", "HS Code", "Qty", "Unit", "Unit Price", "Amount"],
      
      columns: {
        "1_Sr": {
          index: 0,
          label: "Sr",
          purpose: "Serial number for item identification",
          immutable: true,
          alignment: "center",
          fontSize: "12px",
          fontWeight: "500",
          color: "#9ca3af",
          width: "40px",
          cssClass: "text-serial",
          format: "auto-indexed (1, 2, 3...)",
          designNote: "Always auto-generated from index, muted color to reduce visual weight",
        },
        "2_Description": {
          index: 1,
          label: "Description",
          purpose: "Item name and characteristics",
          immutable: true,
          alignment: "left",
          fontSize: "12.5px",
          fontWeight: "400",
          color: "#374151",
          minWidth: "200px",
          cssClass: "text-left",
          format: "text (no styling, plain typography)",
          designNote: "Body text primary color for readability",
        },
        "3_HS_Code": {
          index: 2,
          label: "HS Code",
          purpose: "Harmonized System code for customs classification (6-8 digits)",
          immutable: true,
          alignment: "left",
          fontSize: "12px",
          fontWeight: "500",
          color: "#374151",
          fontFamily: "monospace",
          minWidth: "90px",
          cssClass: "text-monospace",
          format: "6-8 digit code (e.g., 850720 or 8507.20.00)",
          designNote: "Monospace for precision in customs matching, slightly heavier weight for clarity",
        },
        "4_Qty": {
          index: 3,
          label: "Qty",
          purpose: "Quantity of items",
          immutable: true,
          alignment: "right",
          fontSize: "12.5px",
          fontWeight: "500",
          color: "#111827",
          minWidth: "70px",
          cssClass: "text-numeric",
          format: "numeric (without unit suffix in this column)",
          designNote: "Right-aligned for visual sum-ability, semibold for authority",
        },
        "5_Unit": {
          index: 4,
          label: "Unit",
          purpose: "Unit of measurement (PCS, KG, M, L, etc.)",
          immutable: true,
          alignment: "left",
          fontSize: "12px",
          fontWeight: "400",
          color: "#374151",
          minWidth: "70px",
          cssClass: "text-unit",
          format: "abbreviated unit (PCS, KG, M, L, SET, BOX, bundle, etc.)",
          designNote: "Separated from Qty for institutional clarity, regular weight",
        },
        "6_Unit_Price": {
          index: 5,
          label: "Unit Price",
          purpose: "Price per unit (in document currency)",
          immutable: true,
          alignment: "right",
          fontSize: "12.5px",
          fontWeight: "500",
          color: "#111827",
          minWidth: "90px",
          cssClass: "text-numeric",
          format: "currency-formatted (prefix currency symbol, 2 decimals)",
          designNote: "Right-aligned for visual calculation, semibold for authority",
        },
        "7_Amount": {
          index: 6,
          label: "Amount",
          purpose: "Total line amount (Qty × Unit Price)",
          immutable: true,
          alignment: "right",
          fontSize: "12.5px",
          fontWeight: "500",
          color: "#111827",
          minWidth: "90px",
          cssClass: "text-numeric",
          format: "currency-formatted (prefix currency symbol, 2 decimals)",
          designNote: "Right-aligned for visual sum-ability, semibold for authoritative total",
        },
      },

      tableStyle: {
        borderCollapse: "collapse",
        backgroundColor: "#ffffff",
        headerBackground: "transparent",
        headerBorder: "1px solid #d1d5db (bottom only)",
        headerFontSize: "12px",
        headerFontWeight: "600",
        headerTextTransform: "uppercase",
        headerLetterSpacing: "0.6px",
        headerColor: "#6b7280",
        rowPadding: "12px 8px",
        rowBorder: "1px solid #f3f4f6 (bottom)",
        lastRowBorder: "1px solid #d1d5db (bottom)",
        rowHover: "None (clean, no effects)",
        alternatingRows: "No (white background only)",
        roundedCorners: "None (institutional aesthetic)",
        verticalLines: "None (horizontal only)",
      },

      spacing: {
        marginBottom: "32px",
        cellPadding: "12px 8px",
        interRowGap: "border-only (1px)",
      },

      designPrinciples: [
        "Institutional clarity (typography-based hierarchy, not color-based)",
        "Customs audit compliance (HS Code prominence, monospace for precision)",
        "Inventory tracking (Unit separate from Quantity for accuracy)",
        "Bank scrutiny (7 immutable columns, never reorderable)",
        "Minimalism (thin lines only, no boxes, no backgrounds, no hover effects)",
        "Readability (12.5px body, sufficient padding, clear alignment)",
      ],

      cssClasses: {
        table: "items-table",
        header: "items-table-header",
        body: "items-table-body",
        row: "items-table-row",
        serial: "text-serial",
        description: "text-left",
        hsCode: "text-monospace",
        qty: "text-numeric",
        unit: "text-unit",
        unitPrice: "text-numeric",
        amount: "text-numeric",
      },

      immutabilityViolations: [
        "Cannot remove any of 7 columns (violation severity: CRITICAL)",
        "Cannot reorder columns (violation severity: CRITICAL)",
        "Cannot change Sr to manual entry (must remain auto-indexed) (violation severity: CRITICAL)",
        "Cannot merge Qty + Unit into single column (violation severity: HIGH)",
        "Cannot change HS Code alignment or font (violation severity: HIGH)",
        "Cannot add alternating row colors (violation severity: MEDIUM)",
        "Cannot add vertical separator lines (violation severity: MEDIUM)",
      ],
    },

    {
      order: 4,
      section: "FINANCIAL SUMMARY BLOCK (FROZEN INSTITUTIONAL)",
      immutability: {
        status: "FROZEN",
        reason: "Bank authorization requirement + Regulatory total verification + Payment processing compliance",
        violationConsequence: "Will cause payment processing failure and bank document rejection",
        lastModified: "Current Session",
      },
      purpose: "Right-aligned financial summary with 4 rows: Subtotal, Freight, Insurance, Total Invoice Value (bold)",
      applicableToAllDocuments: true,
      
      layout: {
        direction: "Column, right-aligned",
        width: "300px",
        justification: "flex-end (far right of page)",
        marginTop: "32px",
        marginBottom: "32px",
        pageBreakInside: "avoid",
      },

      rowDefinitions: {
        subtotal: {
          label: "Subtotal",
          labelSuffix: "(no colon)",
          value: "Sum of all line items (before freight/insurance)",
          visible: "Always",
          fontSize: "13px",
          fontWeight: "400",
          labelColor: "#374151",
          valueColor: "#111827",
          padding: "8px 0",
          cssClass: "summary-row",
          immutable: true,
        },
        freight: {
          label: "Freight",
          labelSuffix: "(no colon)",
          value: "Freight charges (in document currency)",
          visible: "Only if freightCharges > 0",
          fontSize: "13px",
          fontWeight: "400",
          labelColor: "#374151",
          valueColor: "#111827",
          padding: "8px 0",
          cssClass: "summary-row",
          condition: "Optional - conditional render",
          immutable: true,
        },
        insurance: {
          label: "Insurance",
          labelSuffix: "(no colon)",
          value: "Insurance charges (in document currency)",
          visible: "Only if insuranceCharges > 0",
          fontSize: "13px",
          fontWeight: "400",
          labelColor: "#374151",
          valueColor: "#111827",
          padding: "8px 0",
          cssClass: "summary-row",
          condition: "Optional - conditional render",
          immutable: true,
        },
        divider: {
          element: "Horizontal separator line",
          thickness: "1px solid #d1d5db",
          position: "Top border of total row",
          padding: "12px 0 8px 0",
          purpose: "Visual separation before Total Invoice Value (critical for visual hierarchy)",
          height: "0 (border-only element)",
          immutable: true,
        },
        total: {
          label: "Total Invoice Value",
          labelSuffix: "(no colon)",
          value: "Final sum (Subtotal + Freight + Insurance)",
          visible: "Always",
          fontSize: "16px",
          fontWeight: "700",
          labelColor: "#111827",
          valueColor: "#111827",
          padding: "12px 0 8px 0",
          cssClass: "summary-row total",
          emphasis: "BOLD - This is the authorized invoice total",
          immutable: true,
          designNote: "16px 700 is the only bold element in financial section. Sets visual finality.",
        },
      },

      styling: {
        containerBackground: "transparent (white page only)",
        containerBorder: "none",
        containerBoxShadow: "none",
        rowBorders: "1px solid #d1d5db (top of total row only)",
        cellPadding: "8px 0 for lines, 12px 0 for total",
        cellGap: "20px (between label and value)",
        textAlign: "right-aligned values, left-aligned labels (flex justify-content: space-between)",
        hoverEffects: "None (clean, institutional design)",
        backgroundColor: "None (no alternating rows, no shading)",
      },

      cssClasses: {
        container: "summary",
        box: "summary-box",
        row: "summary-row",
        rowTotal: "summary-row total",
        rowDivider: "summary-row divider",
        label: "summary-label",
        value: "summary-value",
      },

      designPrinciples: [
        "Institutional simplicity (only typography, no decoration)",
        "Right-alignment (visual standard for financial totals)",
        "Bold total only (16px 700 is the only emphasis)",
        "Spacing-based hierarchy (divider line, padding changes)",
        "Bank scrutiny compliance (clear final total for authorization)",
        "No boxes, no shading, no effects (minimal institutional design)",
      ],

      immutabilityViolations: [
        "Cannot change row order (Subtotal → Freight → Insurance → Divider → Total) (violation severity: CRITICAL)",
        "Cannot merge Freight/Insurance into single row (violation severity: HIGH)",
        "Cannot change Total to non-bold (violation severity: CRITICAL)",
        "Cannot change Total label to anything other than 'Total Invoice Value' (violation severity: HIGH)",
        "Cannot remove divider line before total (violation severity: MEDIUM)",
        "Cannot add background shading or boxes (violation severity: MEDIUM)",
      ],
    },

    {
      order: 5,
      section: "Compliance / Declaration Section",
      purpose: "Legal statements, LC requirements, certifications",
      components: [
        "Standard compliance declarations",
        "LC compliance terms (if LC payment)",
        "Certificate of origin declaration (if COO doc)",
        "Insurance policy declarations (if insurance doc)",
        "Customs bonded status (if applicable)",
        "Export scheme details (if EPCG/Drawback)",
      ],
      styling: "13px normal, left-aligned",
      spacing: "40px margin-bottom",
    },

    {
      order: 6,
      section: "SIGNATURE BLOCK (FROZEN MINIMAL)",
      immutability: {
        status: "FROZEN",
        reason: "Regulatory authorization requirement + Clean institutional aesthetic (no line graphics)",
        violationConsequence: "Will break document authenticity and regulatory compliance",
        lastModified: "Current Session",
      },
      purpose: "Clean signature area with spacing only (no borders) - For [Exporter], spacing, Authorized Signatory",
      applicableToAllDocuments: true,
      designPrinciple: "Institutional minimalism: spacing-based hierarchy, no line graphics",
      components: {
        forLine: {
          element: "For [Exporter Name]",
          fontSize: "12px",
          fontWeight: "500",
          color: "#000000",
          marginBottom: "24px",
          purpose: "Identifies party signing the document",
          immutable: true,
        },
        signatureSpace: {
          element: "Blank space (spacing-based, no border line)",
          height: "60px",
          marginBottom: "8px",
          purpose: "Visual separation space for handwritten signature or stamp",
          note: "No top border - spacing only for clean institutional aesthetic",
          immutable: true,
        },
        authorizedSignatory: {
          element: "Authorized Signatory",
          fontSize: "11px",
          fontWeight: "600",
          color: "#000000",
          textTransform: "uppercase",
          letterSpacing: "0.5px",
          marginTop: "8px",
          purpose: "Title/role label",
          immutable: true,
        },
      },
      layout: {
        container: "Right-aligned block",
        width: "280px",
        textAlign: "right",
        justification: "flex-end",
        marginTop: "48px",
        marginBottom: "32px",
      },
      cssClasses: {
        block: ".signature-block",
        container: ".signature-container",
        label: ".signature-label",
        space: ".signature-space (no border)",
        title: ".signature-title",
      },
      styling: {
        background: "transparent",
        border: "none (no line graphics)",
        padding: "0",
        minHeight: "100px (space + labels only)",
      },
      designPrinciples: [
        "Spacing-based (vertical gaps create visual breathing)",
        "No line graphics (pure institutional aesthetic)",
        "Typography hierarchy (title 26px > labels 12px/11px)",
        "Bottom-right authority style (position + text alignment both right)",
      ],
    },

    {
      order: 7,
      section: "COMPLIANCE FOOTER (FROZEN INSTITUTIONAL)",
      immutability: {
        status: "FROZEN",
        reason: "Regulatory compliance tracking + Export authority reference + Bank audit trail",
        violationConsequence: "Will cause customs clearance delays and regulatory audit issues",
        lastModified: "Current Session",
      },
      purpose: "Small, classic footer with IEC, AD Code, Exchange Rate Ref, and compliance attestation",
      applicableToAllDocuments: true,
      layout: {
        display: "grid",
        gridTemplate: "2 columns (1fr 1fr)",
        gap: "24px vertical, 40px horizontal",
        marginTop: "32px",
        marginBottom: "32px",
        borderTop: "1px solid #f3f4f6",
        borderBottom: "1px solid #f3f4f6",
        padding: "16px 0",
      },
      fields: {
        iec: {
          label: "IEC",
          value: "Exporter's IEC (Import-Export Code) number",
          fontSize: "11px",
          fontWeight: "400",
          labelFontSize: "10px",
          labelFontWeight: "600",
          visible: "Only if iecNo is provided",
          immutable: true,
        },
        adCode: {
          label: "AD Code",
          value: "Assessment Date code (for customs tracking)",
          fontSize: "11px",
          fontWeight: "400",
          labelFontSize: "10px",
          visible: "Only if adCode is provided",
          immutable: true,
        },
        exchangeRateRef: {
          label: "Exchange Rate Ref",
          value: "Reference exchange rate or RBI publication",
          fontSize: "11px",
          fontWeight: "400",
          labelFontSize: "10px",
          visible: "Only if exchangeRateRef is provided",
          immutable: true,
        },
        realizationClause: {
          value: "Compliance attestation statement (full width)",
          fontSize: "10px",
          fontWeight: "400",
          color: "#6b7280",
          lineHeight: "1.5",
          gridColumn: "1 / -1",
          visible: "Always",
          immutable: true,
          designNote: "Small, understated compliance declaration - present but not prominent",
        },
      },
      styling: {
        containerBackground: "transparent",
        containerBorder: "1px solid #f3f4f6 (top + bottom)",
        fontSize: "11px (values), 10px (labels and clause)",
        labelTextTransform: "uppercase",
        labelLetterSpacing: "0.5px",
        fontColor: "#6b7280 (container), #9ca3af (labels), #374151 (values)",
      },
      cssClasses: {
        container: "compliance-footer",
        item: "compliance-footer-item",
        label: "compliance-footer-label",
        value: "compliance-footer-value",
        text: "compliance-footer-text",
      },
      designPrinciples: [
        "Institutional minimalism (10-11px, neutral colors only)",
        "Almost silent presence (subtle but complete)",
        "Regulatory completeness (all export authority references)",
        "Two-column grid (compact, not scattered)",
      ],
    },

    {
      order: 8,
      section: "Footer Compliance Strip",
      purpose: "Professional compliance footer with audit trail and verification data",
      position: "Bottom of every page, below signature block",
      designPrinciple: "Single line, minimal, professional - contains critical metadata",
      components: {
        brand: {
          label: "Generated by [Brand Name]",
          fontSize: "10px",
          fontWeight: "500",
          color: "#374151",
          purpose: "Identifies the system/service that generated the document",
        },
        timestamp: {
          label: "Timestamp (Date & Time)",
          format: "Mon DD, YYYY HH:MM:SS",
          fontSize: "10px",
          fontWeight: "400",
          color: "#9ca3af",
          purpose: "Document creation timestamp for audit trail",
        },
        documentHash: {
          label: "Document Hash (first 16 chars + ...)",
          format: "0x7f3e2d1c9a8b...",
          fontSize: "10px",
          fontWeight: "400",
          color: "#9ca3af",
          fontFamily: "'Courier New', monospace",
          letterSpacing: "0.5px",
          condition: "Optional - only if documentHash provided",
          purpose: "Digital fingerprint for verification and blockchain integration",
        },
        auditId: {
          label: "Audit: [Audit ID]",
          fontSize: "10px",
          fontWeight: "400",
          color: "#9ca3af",
          condition: "Optional - only if auditId provided",
          purpose: "Regulatory audit reference identifier",
        },
      },
      layout: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        gap: "12px",
        flexWrap: "wrap",
        textAlign: "center",
      },
      separators: {
        element: "•",
        color: "#d1d5db",
        between: "Each field",
      },
      styling: {
        fontSize: "10px",
        fontWeight: "400",
        color: "#9ca3af",
        textAlign: "center",
        borderTop: "1px solid #f3f4f6",
        paddingTop: "16px",
        marginTop: "48px",
        lineHeight: "1.4",
      },
      dataFields: {
        brandName: "String, default 'Export Docs'",
        documentTimestamp: "ISO 8601 timestamp, formatted to user locale",
        documentHash: "Optional hex string (displayed first 16 chars)",
        auditId: "Optional audit reference string",
      },
      cssClasses: {
        footer: ".footer",
        content: ".footer-content",
        item: ".footer-item",
        separator: ".footer-separator",
        brand: ".footer-brand",
        hash: ".footer-hash",
      },
      comparison: {
        reference: "Professional audit trail design (SaaS/Enterprise standard)",
        philosophy: "Subtle but powerful - minimal space with maximum information density",
        result: "One-line compliance footer with full document verification capability",
      },
    },
  ],

  globalStyling: {
    pageSize: "A4",
    pageMargins: "20mm all sides",
    fontFamily: "Inter, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', sans-serif",
    fontSizeBody: "13px",
    lineHeightBody: "1.6",
    colorPrimary: "#111827",
    colorSecondary: "#374151",
    colorTertiary: "#6b7280",
    colorAccent: "#4b5563",
    colorBorder: "#d1d5db",
    colorBorderLight: "#f3f4f6",
    colorBackground: "white",
    accentLineColor: "#111827",
    accentLineWeight: "2px",
  },

  typography: {
    h1_DocumentTitle: {
      element: "Doc Title",
      fontSize: "26px",
      fontWeight: "700",
      letterSpacing: "-0.2px",
      color: "#111827",
      usage: "Primary document heading (COMMERCIAL INVOICE, PACKING LIST, etc.)",
    },
    h2_DocumentSubtitle: {
      element: "Document Subtitle",
      fontSize: "13px",
      fontWeight: "500",
      color: "#374151",
      usage: "Invoice number, date line, document reference",
    },
    h3_SectionHeading: {
      element: "Section Heading",
      fontSize: "11px",
      fontWeight: "600",
      textTransform: "uppercase",
      letterSpacing: "0.6px",
      color: "#6b7280",
      usage: "Section labels (EXPORTER / SHIPPER, BUYER / IMPORTER, SHIPMENT DETAILS, etc.)",
    },
    bodyText: {
      element: "Body Text",
      fontSize: "13px",
      fontWeight: "400",
      lineHeight: "1.6",
      color: "#374151",
      usage: "General content, descriptions, addresses",
    },
    labelText: {
      element: "Label Text",
      fontSize: "12px",
      fontWeight: "500",
      color: "#6b7280",
      usage: "Field labels (IEC, GSTIN, Port of Loading, etc.)",
    },
    tableHeader: {
      element: "Table Header",
      fontSize: "12px",
      fontWeight: "600",
      textTransform: "uppercase",
      color: "#111827",
      usage: "Table column headers (Description, HS Code, Quantity, etc.)",
    },
    tableRowText: {
      element: "Table Row Text",
      fontSize: "13px",
      fontWeight: "400",
      color: "#374151",
      usage: "Text content in table cells",
    },
    numericColumnText: {
      element: "Numeric Column Text",
      fontSize: "13px",
      fontWeight: "500",
      textAlign: "right",
      color: "#111827",
      usage: "Quantities, prices, amounts in tables (right-aligned)",
    },
    totalsLabel: {
      element: "Totals Label",
      fontSize: "13px",
      fontWeight: "500",
      color: "#374151",
      usage: "Subtotal, Freight, Insurance, etc. labels",
    },
    grandTotalValue: {
      element: "Grand Total Value",
      fontSize: "15px",
      fontWeight: "700",
      textAlign: "right",
      color: "#111827",
      usage: "Final invoice total, prominent value",
    },
    complianceText: {
      element: "Compliance Text",
      fontSize: "11px",
      fontWeight: "400",
      lineHeight: "1.5",
      color: "#4b5563",
      usage: "Declarations, certifications, legal statements, LC terms",
    },
    signatureTitle: {
      element: "Signature Title",
      fontSize: "12px",
      fontWeight: "600",
      color: "#111827",
      usage: "Signature block labels, authorized signatory",
    },
    footerStrip: {
      element: "Footer Strip",
      fontSize: "10px",
      fontWeight: "400",
      color: "#9ca3af",
      usage: "Footer disclaimers, contact info, regulatory statements",
    },
  },

  fontStack: {
    primary: "Inter",
    fallback: [
      "system-ui",
      "-apple-system",
      "BlinkMacSystemFont",
      "'Segoe UI'",
      "'Helvetica Neue'",
      "sans-serif",
    ],
    cssDeclaration: "font-family: Inter, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', sans-serif;",
  },

  spacing: {
    headerMarginBottom: "32px",
    sectionMarginBottom: "40px",
    itemRowPadding: "12px 8px",
    columnGapWide: "40px",
    columnGapNormal: "32px",
  },

  pageStructure: {
    description: "A4 Safe Print System",
    pageSize: "A4 (210mm × 297mm)",
    margins: {
      top: "20mm",
      left: "18mm",
      right: "18mm",
      bottom: "20mm",
      note: "Standard print margins to ensure content stays within safe zone",
    },
    verticalRhythm: {
      sectionSpacing: "32px",
      rowSpacing: "8px",
      description: "Consistent vertical rhythm for visual hierarchy and flow",
    },
    printSafety: {
      minMarginFromEdge: "18mm",
      maxContentWidth: "174mm",
      maxContentHeight: "257mm",
      bleedAvoidance: "5mm safe zone around all edges",
    },
    pageBreakRules: {
      avoidBreakInside: [
        ".container",
        ".header",
        ".info-section",
        ".shipment-details",
        "table",
        ".summary-box",
        ".footer",
      ],
      columnBreakAvoid: "Never force breaks within critical sections",
    },
  },

  sectionLayoutPattern: {
    name: "Universal Section Pattern",
    description: "STANDARD section structure for all content blocks across all 7 document types",
    purpose: "Create clean, scannable, consistent sections without any visual clutter",
    applicableToAllDocuments: true,
    applicableToAllSections: true,
    template: `
      SECTION TITLE (uppercase 11px 600)
      ----------------------------------
      Content
    `,
    structure: {
      sectionTitle: {
        element: "Section header/title",
        fontSize: "11px",
        fontWeight: "600",
        color: "#6b7280",
        textTransform: "uppercase",
        letterSpacing: "0.6px",
        marginBottom: "12px",
        paddingBottom: "12px",
        marginTop: "0",
        display: "block",
        cssClass: ".section-title (or h3 inside .info-section, .items-section)",
      },
      divider: {
        element: "Thin separator line (border-bottom)",
        thickness: "1px",
        color: "#e5e7eb",
        position: "Below section title (integral part of title styling)",
        purpose: "Visual separation without heavy styling",
        purpose2: "Signals end of title, start of content",
      },
      content: {
        element: "Section content block",
        styling: "No background boxes, no grey areas, no heavy borders",
        margin: "Top: 0 (tight against divider)",
        background: "Transparent",
        border: "None",
      },
    },
    cssImplementation: {
      classSelector: ".section-title",
      alternativeSelectors: [
        ".info-section h3",
        ".items-section h3",
        "h3 (within content sections)",
      ],
      styles: {
        fontSize: "11px",
        fontWeight: "600",
        color: "#6b7280",
        textTransform: "uppercase",
        letterSpacing: "0.6px",
        marginBottom: "12px",
        paddingBottom: "12px",
        borderBottom: "1px solid #e5e7eb",
        marginTop: "0",
        display: "block",
      },
    },
    appliedToSections: [
      "Exporter / Shipper",
      "Buyer / Importer",
      "Line Items",
      "Shipment Details",
      "Financial Summary",
      "Compliance / Declaration",
      "Insurance Details",
      "LC Terms",
      "Any content section in any document",
    ],
    appliedToDoucuments: [
      "Commercial Invoice",
      "Packing List",
      "Shipping Bill",
      "Declaration / Undertaking",
      "Certificate of Origin",
      "Insurance Declaration",
      "LC Supporting Documents",
    ],
    designPrinciples: [
      "NEVER boxed",
      "NEVER grey background",
      "NEVER heavy borders",
      "Only spacing + thin divider line (1px)",
      "Minimal: Only text and 1px lines",
      "Clean, scannable, professional layout",
      "Consistent across all documents",
    ],
    examples: {
      example1: {
        title: "EXPORTER / SHIPPER",
        divider: "─────────────────",
        content: "Company Name\nAddress\nIEC/GSTIN",
      },
      example2: {
        title: "LINE ITEMS",
        divider: "──────────",
        content: "Table with product descriptions",
      },
    },
  },

  tableSystem: {
    description: "Enterprise-grade table system (reusable across all documents)",
    purpose: "Professional, minimal tables for invoices, packing lists, insurance docs",
    principle: "Horizontal lines only - no grid borders",
    borders: {
      headerBorder: {
        element: "Header row bottom border",
        thickness: "1px",
        color: "#d1d5db",
        position: "Bottom of <thead>",
      },
      rowBorder: {
        element: "Data row bottom border",
        thickness: "1px",
        color: "#f3f4f6",
        position: "Bottom of each <td>",
        purpose: "Light visual separation between rows",
      },
      lastRowBorder: {
        element: "Last row bottom border",
        thickness: "1px",
        color: "#d1d5db",
        position: "Bottom of last <tr> in <tbody>",
        purpose: "Slightly darker line to close table",
      },
      noBorders: {
        vertical: "Never",
        gridLines: "Never",
        outside: "Never",
      },
    },
    columnAlignment: {
      text: {
        class: ".text-left",
        align: "text-align: left",
        applies: ["Description", "Item name", "Address", "General content"],
      },
      numeric: {
        class: ".text-numeric",
        align: "text-align: right",
        fontVariant: "tabular-nums",
        applies: ["Quantity", "Unit Price", "Amount", "Total", "Any number"],
        fontWeight: "500",
        color: "#111827",
      },
      hsCode: {
        class: ".text-monospace",
        align: "text-align: left",
        fontFamily: "'Courier New', 'Monaco', 'Menlo', monospace",
        fontSize: "12px",
        fontWeight: "500",
        color: "#374151",
        letterSpacing: "0.1px",
        applies: ["HS Code", "Product Code", "SKU", "Any code-like content"],
      },
    },
    styling: {
      headerFontSize: "12px",
      headerFontWeight: "600",
      headerTextTransform: "uppercase",
      headerLetterSpacing: "0.5px",
      headerColor: "#111827",
      rowFontSize: "13px",
      rowFontWeight: "400",
      rowColor: "#374151",
      padding: "12px 8px per cell",
      borderCollapse: "collapse",
      margin: "16px above table",
    },
    usageAcross: [
      "Commercial Invoice - Line items table",
      "Packing List - Contents table",
      "Insurance Declaration - Coverage items",
      "Any document with structured data",
    ],
  },

  financialSummaryBlock: {
    description: "Stripe-style financial summary (right-aligned, minimal, no boxes)",
    purpose: "Display itemized financial breakdown - subtotal, fees, total",
    designPrinciple: "Clean, minimal design using spacing and typography only",
    principle: "No shaded boxes, no heavy borders, just right-aligned spacing",
    layout: {
      direction: "Column",
      alignment: "right (flex: justify-content: flex-end)",
      width: "300px",
      marginTop: "32px",
      marginBottom: "32px",
      gap: "20px between label and value",
    },
    structure: [
      {
        row: "Subtotal",
        label: "Subtotal:",
        value: "Sum of all line items",
        fontSize: "13px",
        fontWeight: "500",
        labelColor: "#374151",
        valueColor: "#111827",
        padding: "8px 0",
        alwaysVisible: true,
      },
      {
        row: "Freight (optional)",
        label: "Freight:",
        value: "Freight charges",
        condition: "Only if freightCharges > 0",
        fontSize: "13px",
        fontWeight: "500",
        labelColor: "#374151",
        valueColor: "#111827",
        padding: "8px 0",
      },
      {
        row: "Insurance (optional)",
        label: "Insurance:",
        value: "Insurance charges",
        condition: "Only if insuranceCharges > 0",
        fontSize: "13px",
        fontWeight: "500",
        labelColor: "#374151",
        valueColor: "#111827",
        padding: "8px 0",
      },
      {
        row: "Divider (visual separator)",
        element: "Border line only",
        thickness: "1px",
        color: "#d1d5db",
        position: "Top border",
        padding: "12px 0 8px 0",
        margin: "4px 0",
        height: "0 (cosmetic only)",
      },
      {
        row: "Total",
        label: "Total:",
        value: "Final invoice total",
        fontSize: "15px",
        fontWeight: "700",
        labelColor: "#111827",
        valueColor: "#111827",
        padding: "12px 0",
        emphasis: "Bold and prominent",
        alwaysVisible: true,
      },
    ],
    styling: {
      containerBackground: "transparent",
      containerBorder: "none",
      containerBoxShadow: "none",
      containerPadding: "0",
      rowDisplay: "flex",
      rowJustifyContent: "space-between",
      rowBorder: "none (except divider row has border-top)",
      textAlign: "right",
    },
    cssClasses: {
      container: ".summary",
      box: ".summary-box",
      row: ".summary-row",
      dividerRow: ".summary-row.divider",
      totalRow: ".summary-row.total",
      label: ".summary-label",
      value: ".summary-value",
    },
    comparison: {
      reference: "Stripe invoice design",
      philosophy: "Rely on spacing and typography, not decoration",
      result: "Professional, enterprise-grade financial summaries",
    },
  },

  signatureBlock: {
    description: "Right-aligned signature/authorization block with space for handwriting or stamp",
    purpose: "Provide official authorization and optional digital verification for documents",
    position: "Bottom right, above footer",
    designPrinciple: "Minimal, clean space with no decoration - focus on functionality",
    layout: {
      alignment: "Right (flex: justify-content: flex-end)",
      width: "280px",
      text_align: "center",
      marginTop: "48px",
      marginBottom: "32px",
      pageBreakAvoid: "page-break-inside: avoid",
    },
    components: {
      forLine: {
        text: "For [Exporter Legal Name]",
        fontSize: "12px",
        fontWeight: "500",
        color: "#374151",
        marginBottom: "24px",
        purpose: "Identifies the party authorizing the document",
      },
      signatureSpace: {
        element: "Blank space with 1px top border",
        height: "60px",
        borderTop: "1px solid #d1d5db",
        marginBottom: "8px",
        purpose: "Space for handwritten signature or official stamp/seal",
      },
      authorizedSignatory: {
        label: "AUTHORIZED SIGNATORY",
        fontSize: "11px",
        fontWeight: "600",
        color: "#111827",
        textTransform: "uppercase",
        letterSpacing: "0.5px",
        marginBottom: "4px",
      },
      signatoryName: {
        element: "Signatory name (printed)",
        fontSize: "11px",
        fontWeight: "500",
        color: "#374151",
        marginBottom: "16px",
        condition: "Optional - only if signatoryName provided",
      },
      documentHash: {
        element: "Digital hash reference for verification",
        fontSize: "9px",
        color: "#9ca3af",
        fontFamily: "'Courier New', monospace",
        marginTop: "12px",
        paddingTop: "8px",
        borderTop: "1px solid #f3f4f6",
        wordBreak: "break-all",
        lineHeight: "1.3",
        condition: "Optional - only if documentHash provided in invoice data",
        purpose: "Blockchain/verification reference for digital signatures",
        example: "Hash: 0x7f3e2d1c9a8b5f6e4d3c2b1a0f9e8d7c",
      },
    },
    cssClasses: {
      block: ".signature-block",
      container: ".signature-container",
      label: ".signature-label",
      space: ".signature-space",
      title: ".signature-title",
      name: ".signature-name",
      hash: ".signature-hash",
    },
    styling: {
      background: "transparent",
      border: "none",
      padding: "0",
      minHeight: "140px (includes space + labels + hash)",
      lineHeight: "1.4 for text, 1.3 for hash",
    },
    dataFields: {
      signatoryName: "Optional from exporter object",
      documentHash: "Optional from exporter object",
    },
    minimumContent: [
      "For [Company Name]",
      "Signature space (60px height)",
      "Authorized Signatory label",
    ],
  },

  footerComplianceStrip: {
    description: "Single-line professional compliance footer with audit trail metadata",
    purpose: "Display document verification, audit, and creation information",
    position: "Bottom of every page, below signature block",
    designPrinciple: "Subtle but powerful - minimal space with maximum information density",
    visual: "Single line, 10px grey text, centered, bullet-separated fields",
    layout: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      gap: "12px",
      flexWrap: "wrap",
      textAlign: "center",
      lineHeight: "1.4",
    },
    fields: {
      brand: {
        label: "Generated by [Brand Name]",
        fontSize: "10px",
        fontWeight: "500",
        color: "#374151",
        always: true,
        example: "Generated by Export Docs",
      },
      timestamp: {
        label: "Formatted timestamp",
        format: "Mon DD, YYYY HH:MM:SS (24-hour)",
        fontSize: "10px",
        fontWeight: "400",
        color: "#9ca3af",
        always: true,
        example: "Feb 16, 2026 14:35:42",
      },
      documentHash: {
        label: "Document hash (first 16 chars)",
        format: "0x7f3e2d1c9a8b5f6e...",
        fontSize: "10px",
        fontFamily: "'Courier New', monospace",
        color: "#9ca3af",
        letterSpacing: "0.5px",
        condition: "Optional - only if documentHash provided",
        purpose: "Digital fingerprint for blockchain/verification systems",
      },
      auditId: {
        label: "Audit ID reference",
        format: "Audit: [ID]",
        fontSize: "10px",
        color: "#9ca3af",
        condition: "Optional - only if auditId provided",
        purpose: "Regulatory audit trail reference",
      },
    },
    separators: {
      element: "• (bullet)",
      color: "#d1d5db",
      position: "Between each field",
      spacing: "12px gap",
    },
    styling: {
      fontSize: "10px",
      fontWeight: "400",
      color: "#9ca3af",
      textAlign: "center",
      borderTop: "1px solid #f3f4f6",
      paddingTop: "16px",
      marginTop: "48px",
      pageBreakAvoid: "page-break-inside: avoid",
    },
    cssClasses: {
      container: ".footer",
      content: ".footer-content",
      item: ".footer-item",
      separator: ".footer-separator",
      brand: ".footer-brand",
      hash: ".footer-hash",
    },
    dataMapping: {
      brandName: "String from invoice.brandName (default: 'Export Docs')",
      documentTimestamp: "ISO 8601 timestamp, formatted to user timezone",
      documentHash: "Hex string (SHA-256 or similar), first 16 chars displayed",
      auditId: "Alphanumeric reference from invoice.auditId",
    },
    examples: [
      "Generated by Export Docs • Feb 16, 2026 14:35:42 • 0x7f3e2d1c9a8b... • Audit: AUD-2026-001234",
      "Generated by ACME Trade • Jan 01, 2026 09:15:30 • Audit: INV-2026-5678",
      "Generated by Global Exports • Mar 20, 2026 16:42:18 • 0x4a5b6c7d8e9f0a1b...",
    ],
    comparisonReference: "Professional SaaS invoice footer (Stripe, Shopify, enterprise platforms)",
    philosophy: "Minimal visual footprint + Maximum information density + Complete audit trail",
  },
}

/**
 * Implementation Notes:
 *
 * 1. CONSISTENCY
 *    - Every document must include all 9 sections in order
 *    - Sections can be omitted ONLY if marked "condition: ..." (e.g., line items NOT applicable)
 *    - Spacing and styling must match this specification exactly
 *
 * 2. DOCUMENT TYPES & CUSTOM SECTIONS
 *    - Commercial Invoice: All sections + Financial Summary
 *    - Packing List: Sections 1-4 + item table (different columns)
 *    - Shipping Bill: Sections 1-5 + Customs details (section 7)
 *    - Declaration: Sections 1-2 + Declaration text (section 7)
 *    - Certificate of Origin: Sections 1-5 + COO declaration (section 7)
 *    - Insurance Declaration: Sections 1-5 + Insurance details (section 6.2), Declaration (section 7)
 *    - LC Supporting Docs: Sections 1-5 + LC terms (section 7)
 *
 * 3. RENDERING ENGINES
 *    - Primary: Puppeteer + HTML (preferred)
 *    - Fallback: pdf-lib (for resilience)
 *    - All HTML templates MUST strictly follow this layout system
 *
 * 4. MOBILE GENERATION
 *    - This system is optimized for A4 print PDFs
 *    - No responsive breakpoints needed
 *    - PDF output is the primary deliverable
 */
