import { renderHeaderBlock } from "@/lib/renderDocumentLayout"
import { renderSignatureBlock } from "@/lib/renderSignatureBlock"

type HeaderMetaRow = {
  label: string
  value: string
  valueClass?: string
}

type HeaderData = {
  documentTitle: string
  subtitle?: string
  paymentTerms?: string
  metadataRows: HeaderMetaRow[]
}

type SignatureOptions = {
  labelOverride?: string
}

type FooterData = {
  brandName?: string
  timestamp?: string
  documentId?: string
  hash?: string
  leadingText?: string
  customContent?: string
}

type RenderDocumentSkeletonParams = {
  exporter: any
  headerData: HeaderData
  content: string
  summarySection?: string
  signatureOptions?: SignatureOptions
  footerData?: FooterData
}

export const documentSkeletonStyles = `
    .document-wrapper {
      display: flex;
      flex-direction: column;
      min-height: 100%;
      width: 100%;
    }

    .document-content {
      flex-grow: 1;
    }

    .signature-block {
      margin-top: auto;
      page-break-inside: avoid;
      break-inside: avoid;
    }
`

export function renderFooterBlock(footerData?: FooterData): string {
  if (footerData?.customContent) {
    return `<div class="footer">${footerData.customContent}</div>`
  }

  const parts: string[] = []

  if (footerData?.leadingText) {
    parts.push(`<span class="footer-item">${footerData.leadingText}</span>`)
  }

  if (footerData?.brandName) {
    parts.push(`<span class="footer-item">Generated by <span class="footer-brand">${footerData.brandName}</span></span>`)
  }

  if (footerData?.timestamp) {
    parts.push(`<span class="footer-item">Timestamp: ${footerData.timestamp}</span>`)
  }

  if (footerData?.documentId) {
    parts.push(`<span class="footer-item">Document ID: ${footerData.documentId}</span>`)
  }

  if (footerData?.hash) {
    parts.push(`<span class="footer-item footer-hash">Hash: ${footerData.hash}</span>`)
  }

  if (parts.length === 0) {
    parts.push(`<span class="footer-item">System Generated</span>`)
  }

  return `
    <div class="footer">
      <div class="footer-content">
        ${parts.join('<span class="footer-separator">|</span>')}
      </div>
    </div>
  `
}

export function renderDocumentSkeleton({
  exporter,
  headerData,
  content,
  summarySection,
  signatureOptions,
  footerData,
}: RenderDocumentSkeletonParams): string {
  return `
    <div class="document-wrapper">
      ${renderHeaderBlock({ exporter, ...headerData })}

      <div class="document-content">
        ${content}
      </div>

      ${summarySection || ""}

      ${renderSignatureBlock(exporter, signatureOptions)}

      ${renderFooterBlock(footerData)}
    </div>
  `
}
